// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220220024524_AddedThePostModel")]
    partial class AddedThePostModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Shared.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlogImage")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 39,
                            BlogImage = "uploads/placeholder.jpg",
                            Description = "Description for category number 0",
                            Name = "Category number: 0"
                        },
                        new
                        {
                            CategoryID = 40,
                            BlogImage = "uploads/placeholder.jpg",
                            Description = "Description for category number 1",
                            Name = "Category number: 1"
                        },
                        new
                        {
                            CategoryID = 41,
                            BlogImage = "uploads/placeholder.jpg",
                            Description = "Description for category number 2",
                            Name = "Category number: 2"
                        });
                });

            modelBuilder.Entity("Shared.Models.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostImage")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishDate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("PostID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostID = 101,
                            Author = "Oriol",
                            CategoryID = 41,
                            Content = "",
                            Excerpt = "This is an example excerpt for post number1....",
                            IsPublished = true,
                            PostImage = "uploads/placeholder.jpg",
                            PublishDate = "20/02/2022 02:45",
                            Title = "Post number: 1"
                        },
                        new
                        {
                            PostID = 102,
                            Author = "Oriol",
                            CategoryID = 40,
                            Content = "",
                            Excerpt = "This is an example excerpt for post number2....",
                            IsPublished = true,
                            PostImage = "uploads/placeholder.jpg",
                            PublishDate = "20/02/2022 02:45",
                            Title = "Post number: 2"
                        },
                        new
                        {
                            PostID = 103,
                            Author = "Oriol",
                            CategoryID = 41,
                            Content = "",
                            Excerpt = "This is an example excerpt for post number3....",
                            IsPublished = true,
                            PostImage = "uploads/placeholder.jpg",
                            PublishDate = "20/02/2022 02:45",
                            Title = "Post number: 3"
                        },
                        new
                        {
                            PostID = 104,
                            Author = "Oriol",
                            CategoryID = 40,
                            Content = "",
                            Excerpt = "This is an example excerpt for post number4....",
                            IsPublished = true,
                            PostImage = "uploads/placeholder.jpg",
                            PublishDate = "20/02/2022 02:45",
                            Title = "Post number: 4"
                        },
                        new
                        {
                            PostID = 105,
                            Author = "Oriol",
                            CategoryID = 41,
                            Content = "",
                            Excerpt = "This is an example excerpt for post number5....",
                            IsPublished = true,
                            PostImage = "uploads/placeholder.jpg",
                            PublishDate = "20/02/2022 02:45",
                            Title = "Post number: 5"
                        },
                        new
                        {
                            PostID = 106,
                            Author = "Oriol",
                            CategoryID = 41,
                            Content = "",
                            Excerpt = "This is an example excerpt for post number6....",
                            IsPublished = true,
                            PostImage = "uploads/placeholder.jpg",
                            PublishDate = "20/02/2022 02:45",
                            Title = "Post number: 6"
                        },
                        new
                        {
                            PostID = 107,
                            Author = "Oriol",
                            CategoryID = 41,
                            Content = "",
                            Excerpt = "This is an example excerpt for post number7....",
                            IsPublished = true,
                            PostImage = "uploads/placeholder.jpg",
                            PublishDate = "20/02/2022 02:45",
                            Title = "Post number: 7"
                        },
                        new
                        {
                            PostID = 108,
                            Author = "Oriol",
                            CategoryID = 39,
                            Content = "",
                            Excerpt = "This is an example excerpt for post number8....",
                            IsPublished = true,
                            PostImage = "uploads/placeholder.jpg",
                            PublishDate = "20/02/2022 02:45",
                            Title = "Post number: 8"
                        },
                        new
                        {
                            PostID = 109,
                            Author = "Oriol",
                            CategoryID = 41,
                            Content = "",
                            Excerpt = "This is an example excerpt for post number9....",
                            IsPublished = true,
                            PostImage = "uploads/placeholder.jpg",
                            PublishDate = "20/02/2022 02:45",
                            Title = "Post number: 9"
                        },
                        new
                        {
                            PostID = 110,
                            Author = "Oriol",
                            CategoryID = 41,
                            Content = "",
                            Excerpt = "This is an example excerpt for post number10....",
                            IsPublished = true,
                            PostImage = "uploads/placeholder.jpg",
                            PublishDate = "20/02/2022 02:45",
                            Title = "Post number: 10"
                        });
                });

            modelBuilder.Entity("Shared.Models.Post", b =>
                {
                    b.HasOne("Shared.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shared.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
