// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Shared.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlogImage")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 39,
                            BlogImage = "uploads/placeholder.jpg",
                            Description = "Description for category number 0",
                            Name = "Category number: 0"
                        },
                        new
                        {
                            CategoryID = 40,
                            BlogImage = "uploads/placeholder.jpg",
                            Description = "Description for category number 1",
                            Name = "Category number: 1"
                        },
                        new
                        {
                            CategoryID = 41,
                            BlogImage = "uploads/placeholder.jpg",
                            Description = "Description for category number 2",
                            Name = "Category number: 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
